# Generated by Django 4.1 on 2023-12-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0004_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="-"),
        ),
    ]
