# Generated by Django 4.1 on 2023-12-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0006_alter_post_title"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["title"], name="title index"),
        ),
    ]
